WebApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls'))
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    # # ex: /polls/
    # url(r'^$', views.index, name='index'),
    # # ex: /polls/5/
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # # ex: /polls/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    # sample
    url(r'^sample/$', views.sample, name='sample'),
    url(r'^start/$', views.start, name='start'),
    url(r'^test/(?P<uid>([A-Z]|[0-9]){14})/$', views.test, name='test'),

    url(r'^record/(?P<uid>([A-Z]|[0-9]){14})/(?P<a>(60|80|100))/$', views.record_answer, name='record_answer'),
    url(r'^create_new_user/$', views.create_new_user, name='create_new_user'),

]

polls/models.py
from __future__ import unicode_literals

from random import randint

from django.db import models
from django.db.models import Count
from django.utils import timezone
import datetime


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    publish_date = models.DateTimeField('date published');

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.publish_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class EyewitnessStimuli(models.Model):

    CONFIDENCE_SCORE = ( (60, 60), (80, 80), (100, 100), )
    LINEUP_RACE = (('B', 'black'), ('W', 'white'), )
    LINEUP_NUMBER = (
        ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'),
        ('W1', 'W1'), ('W2', 'W2'), ('W3', 'W3'), ('W4', 'W4'), ('W5', 'W5'), ('W6', 'W6'),
    )
    CATEGORY = (('O1', 'O1'), ('Omany', 'Omany'), ('R', 'R'), ('U1', 'U1'), ('F', 'F'), )
    CHOICE = ((1, 1), (2, 2), (3, 3),(4, 4), (5, 5), (6, 6),)

    score = models.IntegerField(choices=CONFIDENCE_SCORE)
    lineup_race = models.CharField(max_length=1, choices=LINEUP_RACE)
    lineup_number = models.CharField(max_length=2, choices=LINEUP_NUMBER)
    category = models.CharField(max_length=10, choices=CATEGORY)
    statement = models.TextField(max_length=100)
    chosen_face = models.IntegerField(choices=CHOICE)
    lineup_order = models.CharField(max_length=14)

    def __str__(self):
        return self.lineup_number+": "+self.statement


class Users(models.Model):
    userId = models.CharField(max_length=14, primary_key=True)

    def __str__(self):
        return self.userId


class Response(models.Model):
    CONFIDENCE_SCORE = ( (60, 60), (80, 80), (100, 100), )

    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    question = models.ForeignKey(EyewitnessStimuli, on_delete=models.CASCADE)
    answer = models.IntegerField(choices=CONFIDENCE_SCORE, null=True)

    def __str__(self):
        return self.user.userId

polls/views.py
import random
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from polls.models import Question, Choice, EyewitnessStimuli, Users, Response
from django.urls import reverse
from django.views import generic
import uuid


# Create your views here.
# def index(request):
#     latest_question_list = Question.objects.order_by('-publish_date')[:5]
#     # output = ', '.join(q.question_text for q in latest_question_list)
#     # template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list' : latest_question_list
#     }
#     # return HttpResponse(template.render(context, request))
#     return render(request, 'polls/index.html', context)
#
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk = question_id)
#     context = {
#         'question' : question
#     }
#     # return HttpResponse("You're looking at question %s." % question_id)
#     return render(request, 'polls/detail.html', context)
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """return last five published question"""
        return Question.objects.order_by('-publish_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


# userId, choices, lineups
def sample(request):

    sample_q = get_object_or_404(EyewitnessStimuli, pk = 3)

    file_path = 'polls/lineups/'
    lineup_number = sample_q.lineup_number
    if lineup_number[0] == 'W':
        file_path += 'faces_white/' + lineup_number[1] + '/'
    else:
        file_path += 'faces_black/' + lineup_number[1] + '/'

    lineup_order = sample_q.lineup_order.split(';')
    img_set_path = []
    chosen_face = ""
    for image_num in lineup_order:
        if int(image_num) == sample_q.chosen_face:
            chosen_face = file_path + image_num + '.jpg'

        img_set_path.append(file_path + image_num + '.jpg')
    stmt = sample_q.statement

    context = {
        # 'sample' : sample_q,
        # 'image_path': file_path,
        'chosen': chosen_face,
        'lineup_order1': img_set_path[:3],
        'lineup_order2': img_set_path[3:],
        'statement': stmt,
    }
    return render(request, 'polls/sample.html', context)


def start(request):

    return render(request, 'polls/start.html')


def create_new_user(request):
    uid = uuid.uuid4().hex[:14].upper()
    while Users.objects.filter(pk=uid).exists():
        uid = uuid.uuid4().hex[:14].upper()

    new_user = Users(userId=uid)
    new_user.save()

    generate_question(new_user)

    context = {
        'uid': uid
    }
    return HttpResponseRedirect(reverse('polls:test', args=(uid,)))


def test(request, uid):
    #q_num = Response.objects.filter(user=)
    user = get_object_or_404(Users, pk=uid)
    q_set = user.response_set.exclude(answer__isnull=True)
    q_num = len(q_set)
    print(q_num)

    if q_num == 6:
        return render(request, 'polls/thankyou.html')
    else:
        response = Response.objects.filter(user=user)[q_num]
        sample_q = response.question

        file_path = 'polls/lineups/'
        lineup_number = sample_q.lineup_number
        if lineup_number[0] == 'W':
            file_path += 'faces_white/' + lineup_number[1] + '/'
        else:
            file_path += 'faces_black/' + lineup_number[1] + '/'

        lineup_order = sample_q.lineup_order.split(';')
        img_set_path = []
        chosen_face = ""
        for image_num in lineup_order:
            if int(image_num) == sample_q.chosen_face:
                chosen_face = file_path + image_num + '.jpg'

            img_set_path.append(file_path + image_num + '.jpg')
        stmt = sample_q.statement
        chosen_face = file_path + '5.jpg'

        context = {
            # 'sample' : sample_q,
            # 'image_path': file_path,
            'chosen': chosen_face,
            'lineup_order1': img_set_path[:3],
            'lineup_order2': img_set_path[3:],
            'statement': stmt,
            'uid': uid,
        }
        return render(request, 'polls/sample.html', context)


def record_answer(request, uid, a):
    ##
    print(a)
    user = get_object_or_404(Users, pk=uid)
    q_set = user.response_set.exclude(answer__isnull=True)
    q_num = len(q_set)

    response = Response.objects.filter(user=user)[q_num]
    response.answer = a
    response.save()

    return HttpResponseRedirect(reverse('polls:test', args=(uid,)))


# helper functions
def generate_question(user):
    chosen_set = []     # track lineup_number that has been used
    score_set = [60,80,100]
    race_set = ['W', 'B']

    question_set = []

    for i in range(6):
        query_set = EyewitnessStimuli.objects.filter(score=score_set[int(i/2)], lineup_race=race_set[int(i % 2)])
        for n in chosen_set:
            query_set = query_set.exclude(lineup_number=n)
        q = random.choice(query_set)
        question_set.append(q)
        chosen_set.append(q.lineup_number)

    order = [0,1,2,3,4,5]
    random.shuffle(order)
    for n in order:
        response = Response(user=user, question=question_set[n])
        response.save()

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="vote" />
</form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

polls/templates/polls/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/sample_style.css' %}" />
</head>
<body>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% load static %}
    <div class="container">
        <!-- <table style="width:100%"> -->
        <div class="row">
            {% for path in lineup_order1 %}
                {% if path == chosen %}
                    <img id="chosen" src="{%  static path %}" class="img-responsive image1">
                {% else %}
                    <img src="{%  static path %}" class="img-responsive image1">
                {% endif %}
            {% endfor %}
        </div>

        <div class="row">
            {% for path in lineup_order2 %}
                {% if path == chosen %}
                    <img id="chosen" src="{%  static path %}" class="img-responsive image1">
                {% else %}
                    <img src="{%  static path %}" class="img-responsive image1">
                {% endif %}
            {% endfor %}
        </div>
    <!--</center>-->
    </div>
    <div class="container">
        <h1>{{ statement }}</h1>
    </div>

    <br>

{#    <div class="container">#}
{#        <div class="row">#}
{#            <button class = "btn btn-primary btn-lg" style="width:33%;" type="button" >60</button>#}
{#            <button class = "btn btn-primary btn-lg" style="width:33%;" type="button" >80</button>#}
{#            <button class = "btn btn-primary btn-lg" style="width:33%;" type="button" >100</button>#}
{#        </div>#}
{#    </div>#}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <form action="{% url 'polls:record_answer' uid 60 %}">
                    <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="60"/>
                </form>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <form action="{% url 'polls:record_answer' uid 80 %}">
                    <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="80"/>
                </form>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <form action="{% url 'polls:record_answer' uid 100 %}">
                    <input type="submit" class="btn btn-primary btn-lg" style="width:100%" value="100"/>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

polls/templates/polls/start.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <title>Welcome Page</title>
</head>
<body>
    <div class="jumbotron text-center" style="background-color: inherit">
        <h1>Welcome!</h1>
        <p> some message here </p>
        <form action="{% url 'polls:create_new_user' %}">
            <input type="submit" value="START"  class = "btn btn-primary btn-lg"/>
        </form>
    </div>
</body>
</html>

polls/templates/polls/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
<h1>{{ uid }}</h1>
</body>
</html>

polls/templates/polls/thankyou.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thank you</title>
</head>
<body>
    <h1>Thank you!</h1>
</body>
</html>